trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email "shunmugalv3@gmail.com"
    git config --global user.name "ShansStark"

    echo "Current GitHub source files:"
    ls -la

    echo "Adding Azure Repos as target repository"
    git remote add azure https://$(AZURE_PAT)@dev.azure.com/v-shund/Stark-Azure-Enterprise/_git/Stark-Azure-Enterprise

    echo "Pushing GitHub latest code to Azure Repos"
    git push azure main --force
  displayName: 'Sync GitHub to Azure Repos'